language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

install:
  - composer install --no-interaction --prefer-source

before_script:
  - mkdir coverage

script:
  - vendor/bin/phpunit --coverage-clover coverage/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml