language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0

# Cache composer
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --prefer-source
  - composer create-project wp-coding-standards/wpcs:dev-master --no-dev -n standards/wpcs
  - ./vendor/bin/phpcs -vvv -w --config-set installed_paths '../../../standards/gios/,../../../standards/wpcs/'

before_script:
  - mkdir coverage

script:
  - vendor/bin/phpcs -n --standard=GIOS ./src
  - vendor/bin/phpunit --coverage-clover coverage/clover.xml

after_script:
  - php vendor/bin/coveralls -v
