dist: trusty

language: php

php:
  - 7.0
  - 7.1

# Cache composer
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --prefer-source

before_script:
  - mkdir coverage

script:
  - vendor/bin/phpcs -s --standard=phpcs.xml ./src
  - vendor/bin/phpunit --coverage-clover coverage/clover.xml

after_script:
  - php vendor/bin/coveralls -v
